#!/bin/bash
# Calculator Version Display Script

echo "=========================================="
echo "      Basic Calculator v1.3.0"
echo "=========================================="
echo ""
echo "Release Date: January 20, 2026"
echo ""
echo "Enhanced Features (v1.3):"
echo "✓ Expression-based mathematical calculations"
echo "✓ Full parentheses support with proper precedence"
echo "✓ Persistent calculation history with auto-scroll"
echo "✓ Independent display and button scaling"
echo "✓ Window size memory across sessions"
echo "✓ Complete keyboard support for all operations"
echo "✓ Professional UI with responsive design"
echo "✓ Dynamic precision for small numbers"
echo "✓ Comprehensive error handling and validation"
echo "✓ Memory safety and leak prevention"
echo "✓ Operator validation and syntax checking"
echo "✓ Settings persistence for all preferences"
echo "✓ Increased menu font size for better readability"
echo "✓ Wayland compatibility improvements"
echo "✓ Modern CSS styling (no deprecated GTK functions)"
echo "✓ SSH authentication setup for developers"
echo ""
echo "=========================================="
